[package]
name = "cyclofraust"
version = "0.1.0"
authors = ["Ben B <bburdette@gmail.com>"]
build = "build.rs"

[dependencies]
portaudio = "0.7.0"
libc = "0.2.0"
tinyosc = "0.0.3"

[build-dependencies]
gcc = "0.3"

