[package]
name = "cyclofraust"
version = "0.1.0"
authors = ["Ben B <bburdette@gmail.com>"]
build = "build.rs"

[dependencies]
portaudio = { git = "https://github.com/mvdnes/portaudio-rs" }
libc = "0.2.0"
tinyosc = "0.0.2"

[build-dependencies]
gcc = "0.3"

